// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[PrimaryKey("MaHd", "MaLk")]
[Table("ChiTietHD")]
public partial class ChiTietHd
{
    [Key]
    [Column("MaHD")]
    [StringLength(5)]
    [Unicode(false)]
    public string MaHd { get; set; }

    [Key]
    [Column("MaLK")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaLk { get; set; }

    public byte? SoLuong { get; set; }

    public int? DonGia { get; set; }

    [ForeignKey("MaHd")]
    [InverseProperty("ChiTietHds")]
    public virtual HoaDon MaHdNavigation { get; set; }

    [ForeignKey("MaLk")]
    [InverseProperty("ChiTietHds")]
    public virtual LinhKien MaLkNavigation { get; set; }
}