// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[PrimaryKey("MaPn", "MaLk")]
[Table("ChiTietPN")]
public partial class ChiTietPn
{
    [Key]
    [Column("MaPN")]
    [StringLength(5)]
    [Unicode(false)]
    public string MaPn { get; set; }

    [Key]
    [Column("MaLK")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaLk { get; set; }

    public int? SoLuongNhap { get; set; }

    public int? DonGiaNhap { get; set; }

    [ForeignKey("MaLk")]
    [InverseProperty("ChiTietPns")]
    public virtual LinhKien MaLkNavigation { get; set; }

    [ForeignKey("MaPn")]
    [InverseProperty("ChiTietPns")]
    public virtual PhieuNhap MaPnNavigation { get; set; }
}