// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[Table("HoaDon")]
public partial class HoaDon
{
    [Key]
    [Column("MaHD")]
    [StringLength(5)]
    [Unicode(false)]
    public string MaHd { get; set; }

    [Column("NgayHD")]
    public DateOnly? NgayHd { get; set; }

    [Required]
    [Column("MaKH")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaKh { get; set; }

    [Required]
    [Column("MaNV")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaNv { get; set; }

    public int? TongTien { get; set; }

    [StringLength(30)]
    public string TrangThai { get; set; }

    [StringLength(50)]
    public string PhuongThucThanhToan { get; set; }

    public DateOnly? NgayThanhToan { get; set; }

    [InverseProperty("MaHdNavigation")]
    public virtual ICollection<ChiTietHd> ChiTietHds { get; set; } = new List<ChiTietHd>();

    [ForeignKey("MaKh")]
    [InverseProperty("HoaDons")]
    public virtual KhachHang MaKhNavigation { get; set; }

    [ForeignKey("MaNv")]
    [InverseProperty("HoaDons")]
    public virtual NhanVien MaNvNavigation { get; set; }
}