// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[Table("KhachHang")]
[Index("Sdt", Name = "IX_KhachHang_SDT")]
[Index("TenKh", Name = "IX_KhachHang_TenKH")]
public partial class KhachHang
{
    [Key]
    [Column("MaKH")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaKh { get; set; }

    [Column("TenKH")]
    [StringLength(30)]
    public string TenKh { get; set; }

    [Column("DChi")]
    [StringLength(50)]
    public string Dchi { get; set; }

    [Column("SDT")]
    [StringLength(10)]
    [Unicode(false)]
    public string Sdt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [InverseProperty("MaKhNavigation")]
    public virtual ICollection<HoaDon> HoaDons { get; set; } = new List<HoaDon>();
}