// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[Table("LinhKien")]
[Index("TenLk", Name = "IX_LinhKien_TenLK")]
public partial class LinhKien
{
    [Key]
    [Column("MaLK")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaLk { get; set; }

    [Column("TenLK")]
    [StringLength(50)]
    public string TenLk { get; set; }

    public DateOnly? NgayNhap { get; set; }

    [Column("TGBH")]
    public byte? Tgbh { get; set; }

    [Required]
    [StringLength(3)]
    [Unicode(false)]
    public string MaLoai { get; set; }

    [Required]
    [Column("MaNSX")]
    [StringLength(5)]
    [Unicode(false)]
    public string MaNsx { get; set; }

    [Column("DVT")]
    [StringLength(10)]
    public string Dvt { get; set; }

    public int? SoLuongTon { get; set; }

    public int? DonGiaBan { get; set; }

    public bool NgungKinhDoanh { get; set; }

    [InverseProperty("MaLkNavigation")]
    public virtual ICollection<ChiTietHd> ChiTietHds { get; set; } = new List<ChiTietHd>();

    [InverseProperty("MaLkNavigation")]
    public virtual ICollection<ChiTietPn> ChiTietPns { get; set; } = new List<ChiTietPn>();

    [ForeignKey("MaLoai")]
    [InverseProperty("LinhKiens")]
    public virtual LoaiLk MaLoaiNavigation { get; set; }

    [ForeignKey("MaNsx")]
    [InverseProperty("LinhKiens")]
    public virtual NhaSanXuat MaNsxNavigation { get; set; }
}