// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[Table("LoaiLK")]
public partial class LoaiLk
{
    [Key]
    [StringLength(3)]
    [Unicode(false)]
    public string MaLoai { get; set; }

    [StringLength(40)]
    public string TenLoai { get; set; }

    [StringLength(100)]
    public string MoTa { get; set; }

    [InverseProperty("MaLoaiNavigation")]
    public virtual ICollection<LinhKien> LinhKiens { get; set; } = new List<LinhKien>();
}