// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[Table("NhanVien")]
public partial class NhanVien
{
    [Key]
    [Column("MaNV")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaNv { get; set; }

    [Column("TenNV")]
    [StringLength(40)]
    public string TenNv { get; set; }

    [StringLength(5)]
    public string GioiTinh { get; set; }

    public DateOnly? NgaySinh { get; set; }

    [Column("SDT")]
    [StringLength(10)]
    [Unicode(false)]
    public string Sdt { get; set; }

    [StringLength(20)]
    public string ChucVu { get; set; }

    [StringLength(20)]
    public string Quyen { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    public DateOnly? NgayVaoLam { get; set; }

    public bool DaNghiViec { get; set; }

    [InverseProperty("MaNvNavigation")]
    public virtual ICollection<HoaDon> HoaDons { get; set; } = new List<HoaDon>();

    [InverseProperty("MaNvNavigation")]
    public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; } = new List<PhieuNhap>();

    [InverseProperty("MaNvNavigation")]
    public virtual TaiKhoan TaiKhoan { get; set; }
}