// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[Table("NhaSanXuat")]
public partial class NhaSanXuat
{
    [Key]
    [Column("MaNSX")]
    [StringLength(5)]
    [Unicode(false)]
    public string MaNsx { get; set; }

    [Column("TenNSX")]
    [StringLength(50)]
    public string TenNsx { get; set; }

    [StringLength(50)]
    public string QuocGia { get; set; }

    [InverseProperty("MaNsxNavigation")]
    public virtual ICollection<LinhKien> LinhKiens { get; set; } = new List<LinhKien>();
}