// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[Table("PhieuNhap")]
public partial class PhieuNhap
{
    [Key]
    [Column("MaPN")]
    [StringLength(5)]
    [Unicode(false)]
    public string MaPn { get; set; }

    public DateOnly? NgayNhap { get; set; }

    [Required]
    [Column("MaNV")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaNv { get; set; }

    [InverseProperty("MaPnNavigation")]
    public virtual ICollection<ChiTietPn> ChiTietPns { get; set; } = new List<ChiTietPn>();

    [ForeignKey("MaNv")]
    [InverseProperty("PhieuNhaps")]
    public virtual NhanVien MaNvNavigation { get; set; }
}