// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

public partial class QL_LinhKien_PC_NETContext : DbContext
{
    public QL_LinhKien_PC_NETContext(DbContextOptions<QL_LinhKien_PC_NETContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ChiTietHd> ChiTietHds { get; set; }

    public virtual DbSet<ChiTietPn> ChiTietPns { get; set; }

    public virtual DbSet<HoaDon> HoaDons { get; set; }

    public virtual DbSet<KhachHang> KhachHangs { get; set; }

    public virtual DbSet<LinhKien> LinhKiens { get; set; }

    public virtual DbSet<LoaiLk> LoaiLks { get; set; }

    public virtual DbSet<NhaSanXuat> NhaSanXuats { get; set; }

    public virtual DbSet<NhanVien> NhanViens { get; set; }

    public virtual DbSet<PhieuNhap> PhieuNhaps { get; set; }

    public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ChiTietHd>(entity =>
        {
            entity.HasKey(e => new { e.MaHd, e.MaLk }).HasName("PK_CTHD");

            entity.Property(e => e.MaHd).IsFixedLength();
            entity.Property(e => e.MaLk).IsFixedLength();

            entity.HasOne(d => d.MaHdNavigation).WithMany(p => p.ChiTietHds)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CTHD_HoaDon");

            entity.HasOne(d => d.MaLkNavigation).WithMany(p => p.ChiTietHds)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CTHD_LinhKien");
        });

        modelBuilder.Entity<ChiTietPn>(entity =>
        {
            entity.HasKey(e => new { e.MaPn, e.MaLk }).HasName("PK_CTPN");

            entity.Property(e => e.MaPn).IsFixedLength();
            entity.Property(e => e.MaLk).IsFixedLength();

            entity.HasOne(d => d.MaLkNavigation).WithMany(p => p.ChiTietPns)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CTPN_LinhKien");

            entity.HasOne(d => d.MaPnNavigation).WithMany(p => p.ChiTietPns)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CTPN_PhieuNhap");
        });

        modelBuilder.Entity<HoaDon>(entity =>
        {
            entity.Property(e => e.MaHd).IsFixedLength();
            entity.Property(e => e.MaKh).IsFixedLength();
            entity.Property(e => e.MaNv).IsFixedLength();
            entity.Property(e => e.PhuongThucThanhToan).HasDefaultValue("Tiền mặt");
            entity.Property(e => e.TongTien).HasDefaultValue(0);
            entity.Property(e => e.TrangThai).HasDefaultValue("Chưa thanh toán");

            entity.HasOne(d => d.MaKhNavigation).WithMany(p => p.HoaDons)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HoaDon_KhachHang");

            entity.HasOne(d => d.MaNvNavigation).WithMany(p => p.HoaDons)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_HoaDon_NhanVien");
        });

        modelBuilder.Entity<KhachHang>(entity =>
        {
            entity.Property(e => e.MaKh).IsFixedLength();
            entity.Property(e => e.Sdt).IsFixedLength();
        });

        modelBuilder.Entity<LinhKien>(entity =>
        {
            entity.Property(e => e.MaLk).IsFixedLength();
            entity.Property(e => e.MaLoai).IsFixedLength();
            entity.Property(e => e.MaNsx).IsFixedLength();
            entity.Property(e => e.SoLuongTon).HasDefaultValue(0);

            entity.HasOne(d => d.MaLoaiNavigation).WithMany(p => p.LinhKiens)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LK_LoaiLK");

            entity.HasOne(d => d.MaNsxNavigation).WithMany(p => p.LinhKiens)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LK_NhaSanXuat");
        });

        modelBuilder.Entity<LoaiLk>(entity =>
        {
            entity.Property(e => e.MaLoai).IsFixedLength();
        });

        modelBuilder.Entity<NhaSanXuat>(entity =>
        {
            entity.Property(e => e.MaNsx).IsFixedLength();
        });

        modelBuilder.Entity<NhanVien>(entity =>
        {
            entity.Property(e => e.MaNv).IsFixedLength();
            entity.Property(e => e.Sdt).IsFixedLength();
        });

        modelBuilder.Entity<PhieuNhap>(entity =>
        {
            entity.Property(e => e.MaPn).IsFixedLength();
            entity.Property(e => e.MaNv).IsFixedLength();

            entity.HasOne(d => d.MaNvNavigation).WithMany(p => p.PhieuNhaps)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PhieuNhap_NhanVien");
        });

        modelBuilder.Entity<TaiKhoan>(entity =>
        {
            entity.Property(e => e.MaNv).IsFixedLength();

            entity.HasOne(d => d.MaNvNavigation).WithOne(p => p.TaiKhoan)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_TaiKhoan_NhanVien");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}