// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace QuanLyLinhKienMayTinh.API.Models;

[Table("TaiKhoan")]
[Index("MaNv", Name = "UQ_TaiKhoan_MaNV", IsUnique = true)]
public partial class TaiKhoan
{
    [Key]
    [Column("TenDN")]
    [StringLength(30)]
    [Unicode(false)]
    public string TenDn { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string MatKhau { get; set; }

    [Required]
    [Column("MaNV")]
    [StringLength(6)]
    [Unicode(false)]
    public string MaNv { get; set; }

    [ForeignKey("MaNv")]
    [InverseProperty("TaiKhoan")]
    public virtual NhanVien MaNvNavigation { get; set; }
}