// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class ChiTietPn
{
    public string MaPn { get; set; }

    public string MaLk { get; set; }

    public int? SoLuongNhap { get; set; }

    public int? DonGiaNhap { get; set; }

    public virtual LinhKien MaLkNavigation { get; set; }

    public virtual PhieuNhap MaPnNavigation { get; set; }
}