// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class ChiTietHd
{
    public string MaHd { get; set; }

    public string MaLk { get; set; }

    public byte? SoLuong { get; set; }

    public int? DonGia { get; set; }

    public virtual HoaDon MaHdNavigation { get; set; }

    public virtual LinhKien MaLkNavigation { get; set; }
}