// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class HoaDon
{
    public string MaHd { get; set; }

    public DateOnly? NgayHd { get; set; }

    public string MaKh { get; set; }

    public string MaNv { get; set; }

    public int? TongTien { get; set; }

    public virtual ICollection<ChiTietHd> ChiTietHds { get; set; } = new List<ChiTietHd>();

    public virtual KhachHang MaKhNavigation { get; set; }

    public virtual NhanVien MaNvNavigation { get; set; }
}