// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class KhachHang
{
    public string MaKh { get; set; }

    public string TenKh { get; set; }

    public string Dchi { get; set; }

    public string Dthoai { get; set; }

    public virtual ICollection<HoaDon> HoaDons { get; set; } = new List<HoaDon>();
}