// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class LinhKien
{
    public string MaLk { get; set; }

    public string TenLk { get; set; }

    public DateOnly? NgayNhap { get; set; }

    public byte? Tgbh { get; set; }

    public string MaLoai { get; set; }

    public string MaNsx { get; set; }

    public string Dvt { get; set; }

    public int? SoLuongTon { get; set; }

    public int? DonGiaBan { get; set; }

    public bool NgungKinhDoanh { get; set; }

    public virtual ICollection<ChiTietHd> ChiTietHds { get; set; } = new List<ChiTietHd>();

    public virtual ICollection<ChiTietPn> ChiTietPns { get; set; } = new List<ChiTietPn>();

    public virtual LoaiLk MaLoaiNavigation { get; set; }

    public virtual NhaSanXuat MaNsxNavigation { get; set; }
}