// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class LoaiLk
{
    public string MaLoai { get; set; }

    public string TenLoai { get; set; }

    public virtual ICollection<LinhKien> LinhKiens { get; set; } = new List<LinhKien>();
}