// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class NhanVien
{
    public string MaNv { get; set; }

    public string TenNv { get; set; }

    public string GioiTinh { get; set; }

    public DateOnly? NgaySinh { get; set; }

    public string Sdt { get; set; }

    public string TenDn { get; set; }

    public string MatKhau { get; set; }

    public string ChucVu { get; set; }

    public string Quyen { get; set; }

    public virtual ICollection<HoaDon> HoaDons { get; set; } = new List<HoaDon>();
}