// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class NhanVien
{
    public string MaNv { get; set; }

    public string TenNv { get; set; }

    public string GioiTinh { get; set; }

    public DateOnly? NgaySinh { get; set; }

    public string Sdt { get; set; }

    public string ChucVu { get; set; }

    public string Quyen { get; set; }

    public string Email { get; set; }

    public DateOnly? NgayVaoLam { get; set; }

    public bool DaNghiViec { get; set; }

    public virtual ICollection<HoaDon> HoaDons { get; set; } = new List<HoaDon>();

    public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; } = new List<PhieuNhap>();

    public virtual TaiKhoan TaiKhoan { get; set; }
}