// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class NhaSanXuat
{
    public string MaNsx { get; set; }

    public string TenNsx { get; set; }

    public string QuocGia { get; set; }

    public string Sdt { get; set; }

    public virtual ICollection<LinhKien> LinhKiens { get; set; } = new List<LinhKien>();

    public virtual ICollection<PhieuNhap> PhieuNhaps { get; set; } = new List<PhieuNhap>();
}