// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class PhieuNhap
{
    public string MaPn { get; set; }

    public DateOnly? NgayNhap { get; set; }

    public string MaNv { get; set; }

    public string MaNsx { get; set; }

    public virtual ICollection<ChiTietPn> ChiTietPns { get; set; } = new List<ChiTietPn>();

    public virtual NhaSanXuat MaNsxNavigation { get; set; }

    public virtual NhanVien MaNvNavigation { get; set; }
}