// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using QuanLyLinhKienMayTinh.Models;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class QL_LinhKien_PC_Context
    {

        [DbFunction("fn_DoanhThuTheoThang", "dbo")]
        public static int? fn_DoanhThuTheoThang(int? Thang, int? Nam)
        {
            using (var db = DataProvider.Ins.GetContext())
            {
                return db.Database
                    .SqlQuery<int?>($"SELECT dbo.fn_DoanhThuTheoThang({Thang}, {Nam}) AS Value")
                    .AsEnumerable()
                    .FirstOrDefault() ?? 0;
            }
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
