// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using QuanLyLinhKienMayTinh.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class QL_LinhKien_PC_Context
    {
        private IQL_LinhKien_PC_ContextProcedures _procedures;

        public virtual IQL_LinhKien_PC_ContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new QL_LinhKien_PC_ContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IQL_LinhKien_PC_ContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class QL_LinhKien_PC_ContextProcedures : IQL_LinhKien_PC_ContextProcedures
    {
        private readonly QL_LinhKien_PC_Context _context;

        public QL_LinhKien_PC_ContextProcedures(QL_LinhKien_PC_Context context)
        {
            _context = context;
        }

        public virtual async Task<int> sp_BaoCaoTonKhoAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_BaoCaoTonKho]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
