// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyLinhKienMayTinh.Models
{
    public partial class sp_BaoCaoTonKhoResult
    {
        public string MaLK { get; set; }
        [StringLength(50)]
        public string TenLK { get; set; }
        public int? SoLuongTon { get; set; }
        [StringLength(10)]
        public string DVT { get; set; }
        public int? DonGiaBan { get; set; }
    }
}
