// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyLinhKienMayTinh.Models;

public partial class TaiKhoan
{
    public int Id { get; set; }

    public string Tendangnhap { get; set; }

    public string Matkhau { get; set; }
}